Update to ember 3.28
BBVAEngineering/ember-network-state pull request #125
Opened 2021-11-23 14:08 UTC by Angel-M-R

2021-11-23 14:22 UTC, adrigzr approved these changes, later dismissed

2021-11-24 07:16 UTC, josex2r requested changes

2021-11-24 07:16 UTC, josex2r commented on README.md
>  export default Component.extend({
Upgrade this to Octane:

```js
export default class MyClass {
    @service network;
}
```

> Ensure that all examples are in Octane way please.

2021-11-24 07:16 UTC, josex2r commented on addon/services/network.js
> +	_timer;
We moved from properties to tracked almost 1 year ago, do not reverse the changes again.

- [ ] Use tracked properties

2021-11-29 07:18 UTC, josex2r submitted a review, later dismissed

2021-11-29 07:26 UTC, adrigzr approved these changes

2021-11-29 07:31 UTC, adrigzr commented on package.json
> +    "lint-staged": "^12.1.2"
Esto es una dep de desarrollo.

2021-11-29 07:31 UTC, adrigzr requested changes
Cambia el package.json

2021-11-29 07:34 UTC, adrigzr requested changes

2021-11-29 07:34 UTC, adrigzr commented on package.json
> +    "ember-task-scheduler": "^2.1.0",
Esta dep no veo que se use.

2021-11-29 07:34 UTC, adrigzr commented on package.json
> +    "ember-cli-htmlbars": "^5.7.1",
Esta dep va en dev.

2021-11-29 07:34 UTC, adrigzr commented on package.json
> +    "ember-transition-end": "^2.0.0",
Esta dep no veo que se use, de dónde lo has copiado?

2021-11-29 08:50 UTC, adrigzr approved these changes

2021-11-29 08:51 UTC, merged

2021-11-29 08:56 UTC, adrigzr commented
:tada: This PR is included in version 2.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/ember-network-state/v/2.5.0)
- [GitHub release](https://github.com/BBVAEngineering/ember-network-state/releases/tag/v2.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: